### ISSUE TITLE
模型不收敛

### ISSUE THREAD

**Issue by fightseed** [bubbliiiing/Mobilenet-SSD-Essay#1]
作者你好，非常感谢你的开源。
我使用你的代码训练模型，没有使用预训练模型进行训练，取消了早停，并使用如下参数：
        Freeze_epoch = 0
        Epoch = 200
        BATCH_SIZE = 16
        learning_rate_base = 1e-3
发现在voc0712下loss收敛到5点几后就无法再收敛，而预训练模型loss能达到2点几，请问预训练模型是怎么训练的

**Comment by bubbliiiing** [comment]
我用了主干的预训练权重

**Comment by fightseed** [comment]
感谢作者的回复，我是小白，能不能做个教程讲解一下使用主干的预训练权重进行迁移学习

**Comment by bubbliiiing** [comment]
你可以去keras application库下载一下mobilenet的预训练权重，和正常权重一样用load_weights载入就可以

**Comment by fightseed** [comment]
好的，非常感谢作者
